services:
    Bref\Messenger\Service\ConsumerProvider:
        arguments:
            - ~ # Consumer[]

    Bref\Messenger\Service\TypeProvider:
        arguments:
            - !tagged_iterator bref_messenger.type_provider

    Bref\Messenger\Service\BrefWorker:
        public: true
        arguments:
            - '@Bref\Messenger\Service\TypeProvider'
            - '@Bref\Messenger\Service\ConsumerProvider'

    Bref\Messenger\Service\BusDriver: '@Bref\Messenger\Service\SimpleBusDriver'
    Bref\Messenger\Service\SimpleBusDriver:
        arguments:
            - '@logger'

    Bref\Messenger\Service\Sqs\SqsConsumer:
        abstract: true
        arguments:
            - '@Bref\Messenger\Service\BusDriver'
            - ~ # MessageBus
            - ~ # Serializer
            - ~ # TransportName
            - ~ # EventDispatcher

    Bref\Messenger\Service\Sns\SnsConsumer:
        abstract: true
        arguments:
            - '@Bref\Messenger\Service\BusDriver'
            - ~ # MessageBus
            - ~ # Serializer
            - ~ # TransportName
            - ~ # EventDispatcher

    Bref\Messenger\Service\S3\S3Consumer:
        abstract: true
        arguments:
            - '@Bref\Messenger\Service\BusDriver'
            - ~ # MessageBus
            - ~ # Serializer
            - ~ # TransportName
            - ~ # EventDispatcher
