services:
    Bref\Messenger\Service\ConsumerProvider:
        arguments:
            - ~ # Consumer[]

    Bref\Messenger\Service\TypeProvider:
        arguments:
            - !tagged_iterator bref_messenger.type_provider

    Bref\Messenger\Service\BrefWorker:
        public: true
        arguments:
            - '@Bref\Messenger\Service\TypeProvider'
            - '@Bref\Messenger\Service\ConsumerProvider'

    Bref\Messenger\Service\AbstractConsumer:
        abstract: true
        arguments:
            - '@logger'
            - ~ # MessageBus
            - ~ # Serializer
            - ~ # TransportName
            - ~ # EventDispatcher

    Bref\Messenger\Service\Sqs\SqsConsumer:
        parent: Bref\Messenger\Service\AbstractConsumer
        abstract: true

    Bref\Messenger\Service\Sns\SnsConsumer:
        parent: Bref\Messenger\Service\AbstractConsumer
        abstract: true

    Bref\Messenger\Service\S3\S3Consumer:
        parent: Bref\Messenger\Service\AbstractConsumer
        abstract: true

