services:
    Bref\Messenger\Service\ConsumerProvider:
        arguments:
            - ~ # Consumer[]

    Bref\Messenger\Service\TypeProvider:
        arguments:
            - !tagged_iterator bref_messenger.type_provider

    Bref\Messenger\Service\BrefWorker:
        public: true
        arguments:
            - '@Bref\Messenger\Service\TypeProvider'
            - '@Bref\Messenger\Service\ConsumerProvider'

    Bref\Messenger\Service\BusDriver: '@Bref\Messenger\Service\SimpleBusDriver'
    Bref\Messenger\Service\SimpleBusDriver:
        arguments:
            - '@logger'
